[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "autocheck"
version = "0.1.0"
description = "Auto-checking helpers for IDS tutorials"
requires-python = ">=3.8"
